Numpy  module 

Below cell is command to download numpy

In [1]:
pip install numpy

^C
Note: you may need to restart the kernel to use updated packages.


below this cell is way to import the numpy

In [3]:
import numpy as np

In [5]:
x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)

In [7]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
arrat=np.arange(15).reshape(3,5)
print(arrat)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
